"""
Base strategy — the blueprint that all trading strategies must follow.

Every strategy in this bot inherits from BaseStrategy. Think of it like a
template: it defines WHAT methods a strategy must have, but each strategy
decides HOW to implement them.

This uses Python's ABC (Abstract Base Class) module. An abstract class is
one that cannot be used on its own — you MUST create a subclass that fills
in the abstract methods. If you forget to implement an abstract method,
Python will raise an error when you try to create an instance.

Why do we need a base class?
    - Consistency: every strategy has the same interface (generate_signals,
      execute_signals), so the rest of the bot can work with ANY strategy
      without knowing the details.
    - Shared logic: execute_signals is the same for every strategy — check
      risk, calculate size, place orders. We write it once here.

Usage:
    from strategies.base_strategy import BaseStrategy

    class MyStrategy(BaseStrategy):
        def generate_signals(self, candidates):
            ...  # your logic here
"""

from abc import ABC, abstractmethod
from typing import Any

from broker.alpaca_client import AlpacaClient


class BaseStrategy(ABC):
    """Abstract base class for all trading strategies.

    Every strategy must be able to:
        1. Generate signals — look at market data and decide what to trade.
        2. Execute signals — turn those decisions into real orders.

    Attributes:
        broker_client: An AlpacaClient instance used to place orders and
                       fetch market data (prices, bars, positions).
        risk_manager:  A risk manager object that controls how much we can
                       trade. It must have:
                         - can_trade(symbol) -> bool
                         - calculate_position_size(symbol, entry_price,
                           stop_loss) -> int
    """

    def __init__(self, broker_client: AlpacaClient, risk_manager: Any) -> None:
        """Initialize the strategy with a broker and risk manager.

        Args:
            broker_client: The AlpacaClient that connects us to the market.
                           Used to place orders and fetch prices.
            risk_manager:  Controls risk. Must have can_trade() and
                           calculate_position_size() methods.
        """
        self.broker_client = broker_client
        self.risk_manager = risk_manager

    @abstractmethod
    def generate_signals(self, candidates: list[dict]) -> list[dict]:
        """Analyze candidates and produce trading signals.

        A "signal" is a recommendation to buy or sell a stock. Each strategy
        implements this differently — some look at momentum, others at mean
        reversion, etc. This is the brain of the strategy.

        Each signal is a dictionary with these keys:
            - symbol (str):      The stock ticker, e.g. "AAPL".
            - action (str):      "buy" or "sell".
            - entry_price (float): The price at which we want to enter.
            - stop_loss (float): The price at which we exit to limit losses.
                                 If the stock drops to this price, we sell
                                 immediately to prevent further damage.
            - take_profit (float): The price at which we exit to lock in
                                   gains. When the stock reaches this price,
                                   we sell to capture the profit.
            - confidence (float): How confident the strategy is in this
                                  signal, from 0.0 (no confidence) to 1.0
                                  (very confident).

        Args:
            candidates: A list of dicts, each representing a stock to
                        evaluate. Typically comes from the screener module
                        and includes symbol, price data, and other metrics.

        Returns:
            A list of signal dicts (described above). May be empty if no
            good opportunities are found.
        """

    def execute_signals(self, signals: list[dict]) -> list[dict]:
        """Turn trading signals into actual orders.

        This is the method that makes things real — it takes the signals
        generated by generate_signals() and:
            1. Checks with the risk manager whether we're allowed to trade.
            2. Calculates the right position size (how many shares to buy).
            3. Places the order through the broker.

        The flow for each signal:
            signal -> risk check -> position sizing -> order placement

        Args:
            signals: A list of signal dicts from generate_signals(). Each
                     must have: symbol, action, entry_price, stop_loss,
                     take_profit, confidence.

        Returns:
            A list of executed trade dicts. Each contains:
                - symbol (str):        The ticker that was traded.
                - action (str):        "buy" or "sell".
                - qty (int):           Number of shares traded.
                - entry_price (float): The price at which we entered.
                - stop_loss (float):   Our stop loss price.
                - take_profit (float): Our take profit target.
                - order (dict):        The raw order response from the broker.
                - status (str):        "executed" or "skipped".
                - skip_reason (str):   Why the trade was skipped (only if
                                       status is "skipped").
        """
        executed_trades: list[dict] = []

        for signal in signals:
            symbol = signal["symbol"]
            action = signal["action"]
            entry_price = signal["entry_price"]
            stop_loss = signal["stop_loss"]
            take_profit = signal["take_profit"]

            # Step 1: Ask the risk manager if we're allowed to trade.
            # The risk manager says no if we've hit the daily profit target
            # or the daily loss limit — protecting us from overtrading.
            if not self.risk_manager.can_trade():
                executed_trades.append({
                    "symbol": symbol,
                    "action": action,
                    "qty": 0,
                    "entry_price": entry_price,
                    "stop_loss": stop_loss,
                    "take_profit": take_profit,
                    "order": None,
                    "status": "skipped",
                    "skip_reason": "Risk manager rejected the trade",
                })
                continue

            # Step 2: Calculate position size — how many shares to buy/sell.
            # We need the account equity (total account value) to figure out
            # how much we can risk. The risk manager uses 1% of equity and
            # the distance to the stop loss to calculate share count.
            account_info = self.broker_client.get_account_info()
            account_equity = account_info["equity"]

            qty = self.risk_manager.calculate_position_size(
                account_equity=account_equity,
                entry_price=entry_price,
                stop_loss_price=stop_loss,
            )

            # If position size is zero, skip — not enough capital or the
            # risk is too high for even a single share.
            if qty <= 0:
                executed_trades.append({
                    "symbol": symbol,
                    "action": action,
                    "qty": 0,
                    "entry_price": entry_price,
                    "stop_loss": stop_loss,
                    "take_profit": take_profit,
                    "order": None,
                    "status": "skipped",
                    "skip_reason": "Position size is zero (insufficient capital)",
                })
                continue

            # Step 3: Place the order through the broker.
            order = _place_order(self.broker_client, symbol, action, qty)

            executed_trades.append({
                "symbol": symbol,
                "action": action,
                "qty": qty,
                "entry_price": entry_price,
                "stop_loss": stop_loss,
                "take_profit": take_profit,
                "order": order,
                "status": "executed",
            })

        return executed_trades


def _place_order(
    broker_client: AlpacaClient,
    symbol: str,
    action: str,
    qty: int,
) -> dict:
    """Place a buy or sell order through the broker.

    This is a small helper that routes to the correct broker method
    based on the action string.

    Args:
        broker_client: The AlpacaClient to place the order through.
        symbol: The stock ticker, e.g. "AAPL".
        action: Either "buy" or "sell".
        qty: Number of shares to trade.

    Returns:
        The order response dict from the broker.

    Raises:
        ValueError: If action is not "buy" or "sell".
    """
    if action == "buy":
        return broker_client.place_market_buy(symbol, qty)
    elif action == "sell":
        return broker_client.place_market_sell(symbol, qty)
    else:
        raise ValueError(f"Unknown action '{action}'. Must be 'buy' or 'sell'.")
